# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  create_assumed_role_credentials:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Generate Assumed Role Credentials
          command: |
            env >> .env
            mkdir .secrets
            docker run --env-file .env brutalsimplicity/cicd-tools:latest aws-assume --role $DEPLOYMENT_ROLE -e >> .secrets/.env

      # This will persist credentials for use in subsequent workflows
      - persist_to_workspace:
          root: '.'
          paths:
            - .secrets

      - run:
          name: Verify Credentials
          command: |
            cat .secrets/.env >> $BASH_ENV
            aws sts get-caller-identity

  build_project:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Build
          command: |
            cat /tmp/workspace/.secrets/.env >> $BASH_ENV
            docker-compose -f docker/docker-compose.cicd.yml build

  test_project:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Build
          command: |
            cat /tmp/workspace/.secrets/.env >> $BASH_ENV
            docker-compose -f docker/docker-compose.cicd.yml run test

workflows:
  build:
    jobs:
      - create_assumed_role_credentials:
          name: Assume AWS Deployment Role
          context: cloudmagick

      - build_project:
          requires:
            - Assume AWS Deployment Role
          name: Build Project
          context: cloudmagick

      - test_project:
          requires:
            - Build Project
          name: Test Project
          context: cloudmagick
