# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  assume_role:
    docker:
      - image: brutalsimplicity/cicd-container:v1.0.0
    steps:
      - run:
          name: Generate Credentials

          # Certain AWS tools may require environment variables are set. This can be done
          # with `$(cat /tmp/workspaces/.secrets/.env)`
          command: |
            mkdir -p /tmp/workspace/.secrets
            aws-assume --role $DEPLOYMENT_ROLE --configure -e >> /tmp/workspace/.secrets/.env
            cp -r ~/.aws /tmp/workspace/.aws
      - run:
          name: Verify Credentials
          command: |
            aws sts get-caller-identity
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - .secrets
            - .aws

  build_test_release:
    docker:
      - image: brutalsimplicity/cicd-container:v1.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: &configure_role
          name: Configure AWS Role
          command: |
            cp -r /tmp/workspace/.aws ~/.aws
      - run: &install
          name: Install
          command: |
            npm ci
      - run: &build
          name: Build
          command: |
            npm ci
            npm run build
      - run:
          name: Test
          command: |
            npm run test
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            # This is how you use a custom SSH key that allows git writes to a repository
            - add_ssh_keys:
                fingerprints:
                  - a6:07:c3:9c:10:b2:9b:fb:f9:99:54:97:07:1f:99:05
            - run:
                name: Configure Git
                command: |
                  git config --global user.name "circleci-deployuser"
                  git config --global user.email "circleci-deployuser@noreply.cloudmagick.com"
            - run:
                name: Release
                command: |
                  RELEASE_TO=dev npm run release

  deploy:
    docker:
      - image: brutalsimplicity/cicd-container:v1.0.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - a6:07:c3:9c:10:b2:9b:fb:f9:99:54:97:07:1f:99:05
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: *configure_role
      - run: *install
      - run:
          name: Deploy
          command: |
            GIT_TAG=<< pipeline.git.tag >> npm run ci:deploy

workflows:
  Semantic_Version_Release:
    jobs:
      - assume_role:
          name: Generate AWS Credentials
          context: cloudmagick

      - build_test_release:
          requires:
            - Generate AWS Credentials
          name: Build and Test Project
          filters:
            branches:
              ignore: main

      - build_test_release:
          requires:
            - Generate AWS Credentials
          name: Build, Test, and Release Project
          filters:
            branches:
              only: main

  Semantic_Version_Deploy:
    jobs:
      - assume_role:
          name: Generate AWS Credentials
          context: cloudmagick
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*\d+\.\d+\.\d+[-+_.][a-z0-9]+.*/

      - deploy:
          requires:
            - Generate AWS Credentials
          name: Deploy << pipeline.git.tag >>
          context: cloudmagick
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*\d+\.\d+\.\d+[-+_.][a-z0-9]+.*/
