# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  create_assumed_role_credentials:
    docker:
      - image: brutalsimplicity/cicd-container:v1.0.0
    steps:
      - checkout
      - run:
          name: Generate Assumed Role Credentials
          command: |
            mkdir .secrets
            aws-assume --role $DEPLOYMENT_ROLE -e >> .secrets/.env

      # This will persist credentials for use in subsequent workflows
      - persist_to_workspace:
          root: '.'
          paths:
            - .secrets

      - run:
          name: Verify Credentials
          command: |
            cat .secrets/.env >> $BASH_ENV
            aws sts get-caller-identity

  build_project:
    docker:
      - image: brutalsimplicity/amazonlinux2-buildcontainer:v1.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Build
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm ci
            npm run build

  test_project:
    docker:
      - image: brutalsimplicity/amazonlinux2-buildcontainer:v1.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Build
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm ci
            npm run build
      - run:
          name: Test
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm run test

  release_project:
    docker:
      - image: brutalsimplicity/amazonlinux2-buildcontainer:v1.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace/
      - run:
          name: Build
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm ci
            npm run build
      - run:
          name: Release
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            n
            npm run release

workflows:
  Release:
    jobs:
      - create_assumed_role_credentials:
          name: Assume AWS Deployment Role
          context: cloudmagick

      - build_project:
          requires:
            - Assume AWS Deployment Role
          name: Build Project
          context: cloudmagick

      - test_project:
          requires:
            - Build Project
          name: Test Project
          context: cloudmagick

      - release_project:
          requires:
            - Test Project
          name: Release Project
          context: cloudmagick
