# yaml-language-server: $schema = https://json.schemastore.org/circleciconfig.json
version: 2.1

jobs:
  release:
    docker:
      - image: brutalsimplicity/cicd-container:v1.0.0
    steps:
      - checkout
      - run:
          name: Generate Assumed Role Credentials
          command: |
            mkdir -p /tmp/workspace/.secrets
            aws-assume --role $DEPLOYMENT_ROLE -e >> /tmp/workspace/.secrets/.env
      - run:
          name: Build
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm ci
            npm run build
      - run:
          name: Test
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm run test
      - add_ssh_keys:
          fingerprints:
            - a6:07:c3:9c:10:b2:9b:fb:f9:99:54:97:07:1f:99:05
      - run:
          name: Configure Git
          command: |
            git config --global user.name "circleci-deployuser"
            git config --global user.email "kory.taborn@gmail.com"
      - run:
          name: Release
          command: |
            $(cat /tmp/workspace/.secrets/.env)
            npm run release

workflows:
  Release:
    jobs:
      - release:
          name: Build, Test, and Release Project
          context: cloudmagick
