version: '3.5'
services:
  project:
    image: brutalsimplicity/prototype-nx-monorepo:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile.build

  test:
    image: brutalsimplicity/prototype-nx-monorepo:latest

    # This ensures that the `build` image is built if this is run on its own
    depends_on:
      - build
    command: 'npm run test'

  deploy:
    image: brutalsimplicity/prototype-nx-monorepo-cicd-container:latest
    build:
      context: .
      dockerfile: Dockerfile.deploy
